### ISSUE TITLE
App crashes when trying to Create post

### ISSUE THREAD

**Issue by jordan-bravo** [circles-project/circles-android#10]
### Steps to reproduce

1. Open app.
2. Click on my "Family" circle.  A post that has been shared with me is visible.
3. Tap the "Create post" box.

App crashes

### Additional info

Expected result: I should be able to create a post.

Logs:

[Circles log c4f4388ca721.txt](https://github.com/user-attachments/files/16016366/Circles.log.c4f4388ca721.txt)

### Application version

1.0.32

### App Store name

F-Droid

### Phone model

Pixel 6

### Operating system version

GrapheneOS 2024062000

### Homeserver

circles.futo.org

### Contact info

@jordanbravo:matrix.org

**Comment by jlariviere1** [comment]
I experience the same issue.  1.0.32 has issues when 1.0.31 did not.
I have a P4a, also running Graphene.  I've tried different settings under Graphene's app info hardening options with no difference.  I've tried different keyboards (in case they're causing the issue, and Circles crashed using two different keyboards).

**Comment by ToughDBlue** [comment]
I too am experiencing this issue. I've never used Circles before and installed it to see if this is something that my family would like to use.

**Comment by ChrisDeardeuff** [comment]
I am also experiencing this.

**Comment by cvwright** [comment]
This one should be fixed in 1.0.33, which starts rolling out today.  Let us know!
